<?php

/**
 * Class-SelectLanguageOnRegister.php
 *
 * @package SelectLanguageOnRegister
 * @link https://github.com/dragomano/select-language-on-register
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2023 Bugo
 * @license https://opensource.org/licenses/BSD-3-Clause The 3-Clause BSD License
 *
 * @version 0.1
 */

namespace Bugo;

/**
 * Generated by SimpleModMaker
 */
class SelectLanguageOnRegister
{
	public function hooks()
	{
		add_integration_function('integrate_load_custom_profile_fields', __CLASS__ . '::loadCustomProfileFields#', false, __FILE__);
		add_integration_function('integrate_register', __CLASS__ . '::register#', false, __FILE__);
	}

	/**
	 * @hook integrate_load_custom_profile_fields
	 */
	public function loadCustomProfileFields()
	{
		global $context, $language, $txt;

		if (empty($context['languages']) || in_array($context['current_action'], array('admin', 'signup')) === false)
			return;

		loadLanguage('Profile');

		$html = '';
		foreach ($context['languages'] as $lang => $data) {
			$html .= '<option value="' . $lang . '"' . ($language == $lang ? ' selected' : '') . '>' . $data['name'] . '</option>';
		}

		$context['custom_fields'][] = array(
			'name' => $txt['language'],
			'desc' => $txt['preferred_language'],
			'input_html' => '<select name="language" id="language">' . $html . '</select>',
			'show_reg' => '2'
		);

		$context['custom_fields_required'] = true;
	}

	/**
	 * @hook integrate_register
	 */
	public function register(&$regOptions)
	{
		$regOptions['register_vars']['lngfile'] = isset($_POST['language']) ? $_POST['language'] : '';
	}
}
